---
- name: Run a sample playbook
  hosts: all
  gather_facts: false
  vars:
    ansible_user: ec2-user
    ansible_ssh_pass: DevOps321
  tasks:
    - name: Print message using loop (list)
      ansible.builtin.debug:
        msg: "Message print: {{ item }}"
      loop : 
        - fruit
        - apple
        - orange
    - name: Print message using loop (range)
      ansible.builtin.debug:
        msg: "output range: {{ item }}"
      loop : "{{ (range(0, 5))}}"
