- hosts: all
  name: Run a sample playbook
  tasks:
    - name: Execute ping
      ping:
    - name: print msg
      ansible.builtin.debug:
      msg : message print sample
  vars:
    ansible_user: ec2-user
    ansible_password: DevOps321

