---
- hosts: all
  name: Run a sample playbook
  tasks:
    - name: Execute ping cmd
      ping:
    - name: print msg
      ansible.builtin.debug:
        msg : message print {{ ansible_user }}
  vars:
    ansible_user: ec2-user
    ansible_password: DevOps321

---
- hosts : all
  name : nested yaml
  tasks:
    - name : print msg
      ansible.builtin.debug:
      msg : printing new yaml