- name: Print register variable
  hosts: all
  tasks:
    - name: store output of shell into register
      ansible.builtin.shell: ls
      register : OUTPUT
    - name: Output print
      ansible.builtin.debug:
        msg: "print output {{ OUTPUT }}"
